# Generated by Django 5.1.3 on 2026-05-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0018_alter_classsubject_unique_together_and_more'),
        ('super_admin', '0004_userprofile_bio_userprofile_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_configs', to='super_admin.college'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='key',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='siteconfig',
            unique_together={('key', 'college')},
        ),
    ]
