# Generated by Django 5.2 on 2025-05-22 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0018_staff_passport"),
        ("super_admin", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_members",
                to="super_admin.college",
            ),
        ),
    ]
