# Generated by Django 5.2 on 2025-05-23 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NonTeachingStaffs", "0004_rename_fullnaame_nonteachingstaff_fullname"),
        ("super_admin", "0004_userprofile_bio_userprofile_designation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonteachingstaff",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="non_teaching_staff",
                to="super_admin.college",
            ),
        ),
    ]
