# Generated by Django 5.1.3 on 2026-05-05 17:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_attendance_college_holiday_college_and_more'),
        ('staffs', '0019_staff_college'),
        ('super_admin', '0004_userprofile_bio_userprofile_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Holiday', 'Holiday'), ('Sunday', 'Sunday')], default='Absent', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('holiday_name', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance_records', to='super_admin.college')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='staffs.staff')),
            ],
            options={
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
