# Generated by Django 5.2 on 2025-05-22 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0031_studentdocument_address_proof_and_more"),
        ("super_admin", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="super_admin.college",
            ),
        ),
    ]
