# Generated by Django 5.1.3 on 2026-05-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_student_aay_beneficiary_student_academic_stream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='distance_to_school',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_education',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_education_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
